/*
 * ADC_program.c
 *
 *  Created on: Mar 19, 2021
 *      Author: Kishk
 */

#include "../../Services/STD_TYPES.h"
#include "../../Services/BIT_MATHS.h"

#include "ADC_interface.h"
#include "ADC_private.h"
#include "ADC_config.h"



void ADC_voidInit(void){
	/* SET VOLTAGE REF */
#if ADC_VOLTAGE_REF == ADC_AREF_INTERNAL_OFF
	CLR_BIT(ADMUX , REFS0);
	CLR_BIT(ADMUX , REFS1);

#elif ADC_VOLTAGE_REF == ADC_AVCC_5V
	SET_BIT(ADMUX , REFS0);
	CLR_BIT(ADMUX , REFS1);

#elif ADC_VOLTAGE_REF == ADC_INTERNAL_VREF
	SET_BIT(ADMUX , REFS0);
	SET_BIT(ADMUX , REFS1);
#endif

	/* SET ADC PRESENTATION ADJUSTMENT */

#if ADC_PRESENTATION_ADJUSTMENT == ADC_RIGHT_ADJUSTMENT
	CLR_BIT(ADMUX , ADLAR);
#elif ADC_PRESENTATION_ADJUSTMENT == ADC_LEFT_ADJUSTMENT
	SET_BIT(ADMUX , ADLAR);
#endif

	/* SET ADC CHANNEL */

#if ADC_CHANNEL == ADC_ADC0_PORTA_PIN0
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC1_PORTA_PIN1
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC2_PORTA_PIN2
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC3_PORTA_PIN3
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC4_PORTA_PIN4
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC5_PORTA_PIN5
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC6_PORTA_PIN6
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC7_PORTA_PIN7
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC0_ADC0_DIFFERNTIAL_10x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC1_ADC0_DIFFERNTIAL_10x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC0_ADC0_DIFFERNTIAL_200x
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC1_ADC0_DIFFERNTIAL_200x
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC2_ADC2_DIFFERNTIAL_10x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC3_ADC2_DIFFERNTIAL_10x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);


#elif ADC_CHANNEL == ADC_ADC2_ADC2_DIFFERNTIAL_200x
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC3_ADC2_DIFFERNTIAL_200x
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC0_ADC1_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC1_ADC1_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC2_ADC1_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC3_ADC1_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC4_ADC1_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC5_ADC1_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC6_ADC1_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC7_ADC1_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC0_ADC2_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC1_ADC2_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC2_ADC2_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC3_ADC2_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC4_ADC2_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL == ADC_ADC5_ADC2_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#endif

	/*	SET PRESCALLER	*/
#if ADC_PRESCALLER	==	ADC_u8_DIVISION_BY_2
	SET_BIT(ADCSRA , ADPS0);
	CLR_BIT(ADCSRA , ADPS1);
	CLR_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER	==	ADC_u8_DIVISION_BY_4
	CLR_BIT(ADCSRA , ADPS0);
	SET_BIT(ADCSRA , ADPS1);
	CLR_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER	==	ADC_u8_DIVISION_BY_8
	SET_BIT(ADCSRA , ADPS0);
	SET_BIT(ADCSRA , ADPS1);
	CLR_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER	==	ADC_u8_DIVISION_BY_16
	CLR_BIT(ADCSRA , ADPS0);
	CLR_BIT(ADCSRA , ADPS1);
	SET_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER	==	ADC_u8_DIVISION_BY_32
	SET_BIT(ADCSRA , ADPS0);
	CLR_BIT(ADCSRA , ADPS1);
	SET_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER	==	ADC_u8_DIVISION_BY_64
	CLR_BIT(ADCSRA , ADPS0);
	SET_BIT(ADCSRA , ADPS1);
	SET_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER	==	ADC_u8_DIVISION_BY_128
	SET_BIT(ADCSRA , ADPS0);
	SET_BIT(ADCSRA , ADPS1);
	SET_BIT(ADCSRA , ADPS2);

#endif


	/*	ADC INTERRUPT	*/
#if ADC_INTERRUPT == ADC_u8_INTERRUPT_DISABLE
	CLR_BIT(ADCSRA , ADIE);
#elif ADC_INTERRUPT == ADC_u8_INTERRUPT_ENABLE
	SET_BIT(ADCSRA , ADIE);
#endif

	/*	CLEAR ADC INTERRUPT FLAG	*/
	SET_BIT(ADCSRA , ADIF);

	/*	SET ADC MODE	*/
#if ADC_MODE == ADC_u8_SINGLE_MODE
	CLR_BIT(ADCSRA , ADATE);
#elif ADC_MODE == ADC_u8_AUTO_TRIGGER_MODE
	SET_BIT(ADCSRA , ADATE);
#endif


	/*	 AUTO TRIG MODE		*/
#if ADC_AUTO_TRIG_MODE == ADC_u8_FREE_RUNNING_MODE
	CLR_BIT(SFIOR , ADTS0);
	CLR_BIT(SFIOR , ADTS1);
	CLR_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_u8_ANALOG_COMPRATOR_MODE
	SET_BIT(SFIOR , ADTS0);
	CLR_BIT(SFIOR , ADTS1);
	CLR_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_u8_EXT_INTERRUPT0_MODE
	CLR_BIT(SFIOR , ADTS0);
	SET_BIT(SFIOR , ADTS1);
	CLR_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_u8_TIMER0_COMPARE_MODE
	SET_BIT(SFIOR , ADTS0);
	SET_BIT(SFIOR , ADTS1);
	CLR_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_u8_TIMER0_OVERFLOW_MODE
	CLR_BIT(SFIOR , ADTS0);
	CLR_BIT(SFIOR , ADTS1);
	SET_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_u8_TIMER_COMPARE_B_MODE
	SET_BIT(SFIOR , ADTS0);
	CLR_BIT(SFIOR , ADTS1);
	SET_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_u8_TIMER1_OVERFLOW_MODE
	CLR_BIT(SFIOR , ADTS0);
	SET_BIT(SFIOR , ADTS1);
	SET_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_u8_TIMER1_CAPTURE_MODE
	SET_BIT(SFIOR , ADTS0);
	SET_BIT(SFIOR , ADTS1);
	SET_BIT(SFIOR , ADTS2);

#endif


	/* 	ENABLE ADC	*/
	SET_BIT(ADCSRA , ADEN);


}




void ADC_voidEnable(void){
	SET_BIT(ADCSRA , ADEN);
}

void ADC_voidDisable(void){
	CLR_BIT(ADCSRA , ADEN);
}

u16 ADC_u16GetResult(void){
	u16 LOC_u16Result = 0;
	SET_BIT(ADCSRA,ADSC);
	while(GET_BIT(ADCSRA,ADIF) == 0);
#if ADC_PRESENTATION_ADJUSTMENT == ADC_RIGHT_ADJUSTMENT
	LOC_u16Result = ADCL | (ADCH<<8);
#elif ADC_PRESENTATION_ADJUSTMENT == ADC_LEFT_ADJUSTMENT
	LOC_u8Result = ADCH | (ADCL<<8);
#endif
	SET_BIT(ADCSRA , ADIF);
	return LOC_u16Result;
}


u16 ADC_u16GETChannelResult(u8 Copy_u8ADC_Channel){
	/*	CLEAR MUX	*/
	u16 LOC_u16Result = 0;
	Copy_u8ADC_Channel &= 0b00011111;
	ADMUX &= 0b11100000;
	ADMUX |= Copy_u8ADC_Channel ;
	SET_BIT(ADCSRA,ADSC);
	while(GET_BIT(ADCSRA,ADIF) == 0);
#if ADC_PRESENTATION_ADJUSTMENT == ADC_RIGHT_ADJUSTMENT
	LOC_u16Result = ADCL | (ADCH<<8);
#elif ADC_PRESENTATION_ADJUSTMENT == ADC_LEFT_ADJUSTMENT
	LOC_u8Result = ADCH | (ADCL<<8);
#endif
	SET_BIT(ADCSRA , ADIF);
	return LOC_u16Result;

}
